version: "3"

services:
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    environment:
      - PORT=4000
      - AUTH_URL=http://auth-service:4001
      - A_URL=http://service-a:4002
      - B_URL=http://service-b:4003
    ports:
      - 4000:4000
  auth-service:
    container_name: auth-service
    build: ./auth-service
    environment:
      - PORT=4001
      - ACCESS_TOKEN_SECRET=secret
      - REFRESH_TOKEN_SECRET=secret
  service-a:
    container_name: service-a
    build: ./service-a
    environment:
      - PORT=4002
      - AUTH_URL=http://auth-service:4001
      - A_URL=http://service-a:4002
      - B_URL=http://service-b:4003
  service-b:
    container_name: service-b
    build: ./service-b
    environment:
      - PORT=4003
      - AUTH_URL=http://auth-service:4001
      - A_URL=http://service-a:4002
      - B_URL=http://service-b:4003
